version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adventure
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
