const ICONS_DIR = "media/map-icons";
const OUTPUT_FILE = "src/game/map/locations/location-type-image.ts";

const GENERATED_COMMENT = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-map-icon-data-uris.ts
`;

const getIconKey = (filename: string) =>
  filename.toLowerCase().endsWith(".png")
    ? filename.replace(/\.png$/i, "")
    : null;

const encodeIcon = async (key: string, filePath: string) => {
  const data = await Deno.readFile(filePath);
  const base64 = btoa(String.fromCharCode(...new Uint8Array(data)));
  return `  ${key}: "data:image/png;base64,${base64}",`;
};

const main = async () => {
  const out = [GENERATED_COMMENT + "export const locationTypeImage = {"];
  for await (const entry of Deno.readDir(ICONS_DIR)) {
    if (entry.isFile && entry.name.endsWith(".png")) {
      const key = getIconKey(entry.name);
      if (key) {
        out.push(await encodeIcon(key, `${ICONS_DIR}/${entry.name}`));
      }
    }
  }
  out.push("} as const;");
  await Deno.writeTextFile(OUTPUT_FILE, out.join("\n"));
  console.log(`Wrote ${OUTPUT_FILE}`);
};

if (import.meta.main) main();
