name: deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Deno Version
        run: deno --version
      - name: Check formatting
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Test
        run: deno test --allow-all
